# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: propresenter_schemas.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'propresenter_schemas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1apropresenter_schemas.proto\x12\x02rv\"\xa1\x01\n\x0cPresentation\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\x04\x63ues\x18\x03 \x03(\x0b\x32\x07.rv.Cue\x12\x1e\n\x06groups\x18\x0b \x03(\x0b\x32\x0e.rv.SlideGroup\x12\x1a\n\x04\x63\x63li\x18\x04 \x01(\x0b\x32\x0c.rv.CCLIData\x12\"\n\x04info\x18\x05 \x01(\x0b\x32\x14.rv.PresentationInfo\"R\n\nSlideGroup\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x19\n\x06slides\x18\x03 \x03(\x0b\x32\t.rv.Slide\x12\r\n\x05\x63olor\x18\x04 \x01(\t\"C\n\x05Slide\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x1d\n\x08\x65lements\x18\x02 \x03(\x0b\x32\x0b.rv.Element\x12\r\n\x05notes\x18\x03 \x01(\t\"3\n\x07\x45lement\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x1a\n\x04text\x18\x02 \x01(\x0b\x32\x0c.rv.TextData\".\n\x08TextData\x12\x0f\n\x07rtfData\x18\x01 \x01(\t\x12\x11\n\tplainText\x18\x02 \x01(\t\"\x85\x01\n\x08\x43\x43LIData\x12\x12\n\nsongNumber\x18\x01 \x01(\t\x12\x11\n\tsongTitle\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\t\x12\x11\n\tcopyright\x18\x05 \x01(\t\x12\x11\n\tpublisher\x18\x06 \x01(\t\x12\x0c\n\x04year\x18\x07 \x01(\t\"3\n\x10PresentationInfo\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\r\n\x05notes\x18\x02 \x01(\t\"!\n\x03\x43ue\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'propresenter_schemas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRESENTATION']._serialized_start=35
  _globals['_PRESENTATION']._serialized_end=196
  _globals['_SLIDEGROUP']._serialized_start=198
  _globals['_SLIDEGROUP']._serialized_end=280
  _globals['_SLIDE']._serialized_start=282
  _globals['_SLIDE']._serialized_end=349
  _globals['_ELEMENT']._serialized_start=351
  _globals['_ELEMENT']._serialized_end=402
  _globals['_TEXTDATA']._serialized_start=404
  _globals['_TEXTDATA']._serialized_end=450
  _globals['_CCLIDATA']._serialized_start=453
  _globals['_CCLIDATA']._serialized_end=586
  _globals['_PRESENTATIONINFO']._serialized_start=588
  _globals['_PRESENTATIONINFO']._serialized_end=639
  _globals['_CUE']._serialized_start=641
  _globals['_CUE']._serialized_end=674
# @@protoc_insertion_point(module_scope)
